2019-03-26 18:56:58,121 INFO: Ceroc Management startup [in C:\Users\Sam Benson\Documents\Code\python\ceroc\app\__init__.py:45]
2019-03-26 18:58:39,267 INFO: Ceroc Management startup [in C:\Users\Sam Benson\Documents\Code\python\ceroc\app\__init__.py:45]
2019-03-27 07:35:46,818 INFO: Ceroc Management startup [in C:\Users\Sam Benson\Documents\Code\python\ceroc\app\__init__.py:47]
2019-03-27 07:38:19,084 INFO: Ceroc Management startup [in C:\Users\Sam Benson\Documents\Code\python\ceroc\app\__init__.py:47]
2019-03-27 07:43:23,622 INFO: Ceroc Management startup [in C:\Users\Sam Benson\Documents\Code\python\ceroc\app\__init__.py:47]
2019-03-27 08:09:59,747 INFO: Ceroc Management startup [in C:\Users\Sam Benson\Documents\Code\python\ceroc\app\__init__.py:47]
2019-03-27 08:10:05,255 INFO: Route /index called [in C:\Users\Sam Benson\Documents\Code\python\ceroc\app\routes.py:17]
2019-03-27 08:10:05,291 ERROR: Exception on / [GET] [in c:\users\sam benson\documents\code\python\ceroc\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\sam benson\documents\code\python\ceroc\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\sam benson\documents\code\python\ceroc\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\sam benson\documents\code\python\ceroc\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\sam benson\documents\code\python\ceroc\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\sam benson\documents\code\python\ceroc\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\sam benson\documents\code\python\ceroc\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Sam Benson\Documents\Code\python\ceroc\app\routes.py", line 33, in index
    return render_template('index.html', title='Home', posts=posts)
  File "c:\users\sam benson\documents\code\python\ceroc\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\sam benson\documents\code\python\ceroc\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\sam benson\documents\code\python\ceroc\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\sam benson\documents\code\python\ceroc\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\sam benson\documents\code\python\ceroc\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\sam benson\documents\code\python\ceroc\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Sam Benson\Documents\Code\python\ceroc\app\templates\index.html", line 1, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "c:\users\sam benson\documents\code\python\ceroc\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\sam benson\documents\code\python\ceroc\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\users\sam benson\documents\code\python\ceroc\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\users\sam benson\documents\code\python\ceroc\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Users\Sam Benson\Documents\Code\python\ceroc\app\templates\index.html", line 7, in block "content"
    <h1 style='color:pink'>Hi {{ current_user.username }}!</h1>
  File "c:\users\sam benson\documents\code\python\ceroc\venv\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'current_user' is undefined
2019-03-27 08:13:05,619 INFO: Route /index called [in C:\Users\Sam Benson\Documents\Code\python\ceroc\app\routes.py:17]
2019-03-27 08:13:33,916 INFO: Route /index called [in C:\Users\Sam Benson\Documents\Code\python\ceroc\app\routes.py:17]
2019-03-27 08:17:09,057 INFO: Route /index called [in C:\Users\Sam Benson\Documents\Code\python\ceroc\app\routes.py:17]
2019-03-27 10:11:57,041 INFO: Ceroc Management startup [in C:\Users\Sam Benson\Documents\Code\python\ceroc\app\__init__.py:47]
2019-03-27 10:11:58,130 INFO: Route /index called [in C:\Users\Sam Benson\Documents\Code\python\ceroc\app\routes.py:17]
2019-03-27 10:12:26,004 INFO: Route /index called [in C:\Users\Sam Benson\Documents\Code\python\ceroc\app\routes.py:17]
2019-03-27 10:12:40,543 INFO: Route /index called [in C:\Users\Sam Benson\Documents\Code\python\ceroc\app\routes.py:17]
2019-03-27 10:12:48,149 INFO: Route /index called [in C:\Users\Sam Benson\Documents\Code\python\ceroc\app\routes.py:17]
2019-03-27 10:12:58,599 INFO: Route /index called [in C:\Users\Sam Benson\Documents\Code\python\ceroc\app\routes.py:17]
2019-03-27 10:13:04,248 INFO: Route /index called [in C:\Users\Sam Benson\Documents\Code\python\ceroc\app\routes.py:17]
27-Mar-19 12:24:32 INFO: Ceroc Management startup [in C:\Users\Sam Benson\Documents\Code\python\ceroc\app\__init__.py:47]
2019-04-01 19:33:19,050 INFO: Ceroc Management startup [in C:\Users\Sam Benson\Documents\Code\python\ceroc\app\__init__.py:47]
2019-04-01 19:35:50,617 INFO: Ceroc Management startup [in C:\Users\Sam Benson\Documents\Code\python\ceroc\app\__init__.py:47]
2019-04-02 20:03:51,438 INFO: Ceroc Management startup [in c:\Users\Sam Benson\Documents\Code\python\ceroc\app\__init__.py:47]
